### ISSUE TITLE
server drawn labels on shingled images with transparency duplicate on pan

### ISSUE THREAD

**Issue by schneidermichal** [AppGeo/geo#108]
As you can see here - http://194.228.3.81/testing/new-ajax/ - images of shingled services are appended in DIV geo-services-container.

It can be seen nicely on labels when on pan.

Is there any way to avoid appending images?

**Comment by ryanttb** [comment]
Time flies :) shinglesMax should be available in the latest test release

http://test.jquerygeo.com/jquery.geo-1.0.0-test.min.js
