### ISSUE TITLE
xhtml not supported ?

### ISSUE THREAD

**Issue by andreasplesch** [AppGeo/geo#165]
Hello,

I was trying to use the  widget with an xhtml document but kept running into a syntax error in jquery.
Tracking down the error, I finally used the 'simplest' example
http://docs.jquerygeo.com/examples/simplest.html

and transformed it into xhtml by declaring it xhtml and closing tags in the header:
http://plaza-omega.codio.io/jquerygeo/simplestmap/simplest.xhtml

This results in this syntax error:
[16:57:26.562] SyntaxError: An invalid or illegal string was specified @ http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js:4

The same result with jquery 2.1.3:
http://plaza-omega.codio.io/jquerygeo/simplestmap/simplest_jq213.xhtml

Is xhtml supported ?

**Comment by ryanttb** [comment]
As far as I could tell, the only thing that wasn't XHTML compliant was the default attribution text. The latest test build should work.
http://test.jquerygeo.com/simplest.xhtml
Also I noticed that your sample didn't use an XHTML doctype or CDATA markers around the JavaScript. It would still work in browsers but I believe it's non-conforming :)
