### ISSUE TITLE
Polygon with more holes

### ISSUE THREAD

**Issue by schneidermichal** [AppGeo/geo#168]
Hi, I'm trying to append a polygon with more holes. With one hole is everything fine, but with two, it renderes badly. Is it an issue or am I doing something wrong?

http://jsbin.com/fuleterere/2/

Thanks a lot!

**Comment by ryanttb** [comment]
Your code is correct! This is a huge oversight in testing and, I believe, a regression. Here is your code working with the latest test build:

http://jsbin.com/hicapi/2/edit

This will be fixed in rc1 which, even though we just release b2, isn't far away.

Thank you for testing!

**Comment by schneidermichal** [comment]
Hi Ryan, thanks a lot, it works now as I expected.

**Comment by ryanttb** [comment]
Great to hear!
